/**
 * Greenmood V2 — Shared TypeScript Types
 *
 * Types that are NOT generated by Prisma go here.
 * For Prisma-generated types, import from @prisma/client.
 */

// ─── API Response Types ───

export interface ApiResponse<T = unknown> {
  success: boolean
  data?: T
  error?: string
  errors?: string[]
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  total: number
  page: number
  pageSize: number
  hasMore: boolean
}

// ─── AI Generation Types ───

export interface GenerationRequest {
  brief: string
  contentType: string
  markets: string[]
  platforms: string[]
  campaignId?: string
  contentPillarId?: string
}

export interface GeneratedPost {
  text: string
  first_comment: string | null
  hashtags: string | null
  timing: string | null
  notes: string | null
}

export interface GenerationResult {
  title: string
  posts: Record<string, GeneratedPost>
  image_prompts?: string[]
  stories?: string[]
}

// ─── Fact Check Types ───

export interface FactCheckIssue {
  type: 'incorrect_fact' | 'unsupported_claim' | 'restricted_claim' | 'missing_attribution' | 'invented_detail'
  severity: 'critical' | 'warning'
  text: string
  explanation: string
  suggestion: string | null
}

export interface FactCheckResult {
  status: 'pass' | 'fail' | 'warning'
  issues: FactCheckIssue[]
  summary: string
}

// ─── Brand Review Types ───

export interface BrandReviewIssue {
  type: 'tone' | 'formatting' | 'brand_rule' | 'quality'
  severity: 'critical' | 'suggestion'
  text: string
  explanation: string
  suggestion: string
}

export interface BrandReviewResult {
  status: 'pass' | 'needs_revision'
  score: number
  issues: BrandReviewIssue[]
  revisedContent: string | null
  summary: string
}

// ─── Intelligence Types ───

export interface IntelligenceSignal {
  title: string
  source: string
  sourceUrl?: string
  country: string
  category: 'competitor_move' | 'trend' | 'event' | 'content_gap' | 'narrative' | 'product_launch'
  competitor: string | null
  summary: string
  whyItMatters: string
  confidence: 'high' | 'medium' | 'low'
  urgency: 'act_now' | 'this_week' | 'this_month' | 'monitor'
  recommendedAction: string
  recommendedFormat: string
  recommendedChannel: string
  recommendedTiming: string
}

export interface IntelligenceDigest {
  signals: IntelligenceSignal[]
  digest: {
    topSignals: string[]
    competitorHighlights: string[]
    trendSummary: string
    contentOpportunities: string[]
    risksToAvoid: string[]
  }
}

// ─── Calendar Types ───

export interface CalendarEvent {
  id: string
  date: string
  time?: string
  market: string
  platform: string
  status: string
  title?: string
  campaignTitle?: string
  contentPillar?: string
}

// ─── Publishing Types ───

export interface PublishJob {
  id: string
  postId: string
  platform: string
  scheduledAt: Date
  status: 'pending' | 'in_progress' | 'completed' | 'failed' | 'retrying'
  attempts: number
  lastError?: string
}

export interface PublishResult {
  success: boolean
  platformPostId?: string
  platformUrl?: string
  error?: string
}

// ─── Dashboard Types ───

export interface DashboardStats {
  totalPosts: number
  postsThisWeek: number
  pendingApprovals: number
  scheduledPosts: number
  publishedThisMonth: number
  activeAgentRuns: number
  topPerformingPillar?: string
  nextScheduledPost?: {
    id: string
    platform: string
    market: string
    scheduledAt: string
  }
}
